#http://en.wikipedia.org/wiki/List_of_restaurant_chains_in_the_United_States
Table = {
    "Location":{
        "Red Robin": 2,
        "TGI Friday's": 2,
        "TGI Friday's": 0,
        "Burger King": 0,
        "Dunkin' Donuts":2,
        "Corner Bakery Cafe":0,
        "Sonic":0,
        "Cici's":0,
        "In-N-Out Burger":0,
        "Five Guys":0,
        "Portillos":0,
        "Buffalo Wild Wings":0,
        "Mc Donald's":0,
        "Applebee's":1,
        "Hooter's":3,
        "IHOP":4,
        "Chick-fil-A":4,
        "Panera":1,
        "Chipotle":1,
        "Taco Bell":1,
        "Panchero's":4,
        "Outback Steakhouse":0,
        "Lonestar":1,
        "Tumbleweeds":4,
        "Longhorn Steakhouse":4,
        "Chilli's":4,
        "Olive Garden":4,
        "Texas Roadhouse":0,
        "Tilted Kilt":4,
        "Steak and Shake":0,
        "Pizza Hut":1,
        "KFC":1,
        "Long John Silver's":1,
        "Papa John's Pizza":1,
        "Quizno's":1,
        "Subway":0,
        "Starbuck's":5,
        "Chuckie Cheese's":4,
        "Tom and Jerry's":4,
        "Panda Express":1,
        "Charley's Grilled Subs":4,
        "Jimmy John's":0,
        "Taco John's":0,
        "Culver's":4,
        "Domino's":0,
        "Arby's":1,
        "Carl's Jr.":4,
        "Waffle House":4,
        "Denny's":0,
        "Hard Rock":4,
        "Hardee's":4,
        "Jack in the Box":4,
        "Kenny Rogers Roasters":4,
        "Popeye's Chicken":0,
        "Little Caesars":4,
        "Red Lobster":0,
        "Sizzler":4,
        "Ruby Tuesday":0,
        "Tim Horton's":4,
        "PDQ":4,
        "A&W":4,
        "Sbarro":4,
        "Smashburger":4,
        "White Castle":0,
        "Potbelly Sandwich Works":0,
        "Qdoba":0,
        "Noodles and Company":4,
        "Joe's Crab Shack":0,
        "Maid-Rite":1,
        "Old Chicago":1,
        "Wendy's":0,
        "":4,
        "":4,"":4,
        "":4,
        },
        
    "Beverage":["Coke","Pepsi","Dr. Pepper","Mix","Unknown","None"]
}
